services:
  mongodb-pokedex:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/data/db
